/**
 * Indian Cities Database for AbhiBus
 * Maps city names to their AbhiBus IDs used in search URLs.
 * Format: { name, id, state }
 *
 * The AbhiBus URL pattern is:
 *   /bus_search/{origin_name}/{origin_id}/{dest_name}/{dest_id}/{DD-MM-YYYY}/O
 */

const CITIES = {
  "Hyderabad":        { id: 3,    state: "Telangana" },
  "Mumbai":           { id: 4,    state: "Maharashtra" },
  "Bangalore":        { id: 7,    state: "Karnataka" },
  "Bengaluru":        { id: 7,    state: "Karnataka" },
  "Chennai":          { id: 5,    state: "Tamil Nadu" },
  "Delhi":            { id: 68,   state: "Delhi" },
  "New Delhi":        { id: 68,   state: "Delhi" },
  "Pune":             { id: 90,   state: "Maharashtra" },
  "Kolkata":          { id: 71,   state: "West Bengal" },
  "Ahmedabad":        { id: 61,   state: "Gujarat" },
  "Jaipur":           { id: 66,   state: "Rajasthan" },
  "Lucknow":          { id: 73,   state: "Uttar Pradesh" },
  "Goa":              { id: 18,   state: "Goa" },
  "Panaji":           { id: 18,   state: "Goa" },
  "Visakhapatnam":    { id: 1,    state: "Andhra Pradesh" },
  "Vizag":            { id: 1,    state: "Andhra Pradesh" },
  "Vijayawada":       { id: 2,    state: "Andhra Pradesh" },
  "Tirupati":         { id: 10,   state: "Andhra Pradesh" },
  "Coimbatore":       { id: 33,   state: "Tamil Nadu" },
  "Madurai":          { id: 38,   state: "Tamil Nadu" },
  "Mysore":           { id: 25,   state: "Karnataka" },
  "Mysuru":           { id: 25,   state: "Karnataka" },
  "Mangalore":        { id: 27,   state: "Karnataka" },
  "Mangaluru":        { id: 27,   state: "Karnataka" },
  "Hubli":            { id: 22,   state: "Karnataka" },
  "Dharwad":          { id: 23,   state: "Karnataka" },
  "Belgaum":          { id: 24,   state: "Karnataka" },
  "Belagavi":         { id: 24,   state: "Karnataka" },
  "Gulbarga":         { id: 26,   state: "Karnataka" },
  "Kalaburagi":       { id: 26,   state: "Karnataka" },
  "Shimoga":          { id: 28,   state: "Karnataka" },
  "Shivamogga":       { id: 28,   state: "Karnataka" },
  "Davangere":        { id: 29,   state: "Karnataka" },
  "Bellary":          { id: 30,   state: "Karnataka" },
  "Ballari":          { id: 30,   state: "Karnataka" },
  "Bijapur":          { id: 31,   state: "Karnataka" },
  "Vijayapura":       { id: 31,   state: "Karnataka" },
  "Raichur":          { id: 32,   state: "Karnataka" },
  "Nellore":          { id: 11,   state: "Andhra Pradesh" },
  "Guntur":           { id: 12,   state: "Andhra Pradesh" },
  "Kakinada":         { id: 6,    state: "Andhra Pradesh" },
  "Rajahmundry":      { id: 8,    state: "Andhra Pradesh" },
  "Kurnool":          { id: 9,    state: "Andhra Pradesh" },
  "Anantapur":        { id: 13,   state: "Andhra Pradesh" },
  "Kadapa":           { id: 14,   state: "Andhra Pradesh" },
  "Ongole":           { id: 15,   state: "Andhra Pradesh" },
  "Eluru":            { id: 16,   state: "Andhra Pradesh" },
  "Srikakulam":       { id: 17,   state: "Andhra Pradesh" },
  "Warangal":         { id: 19,   state: "Telangana" },
  "Karimnagar":       { id: 20,   state: "Telangana" },
  "Nizamabad":        { id: 21,   state: "Telangana" },
  "Nagpur":           { id: 91,   state: "Maharashtra" },
  "Nashik":           { id: 92,   state: "Maharashtra" },
  "Aurangabad":       { id: 93,   state: "Maharashtra" },
  "Solapur":          { id: 94,   state: "Maharashtra" },
  "Kolhapur":         { id: 95,   state: "Maharashtra" },
  "Indore":           { id: 74,   state: "Madhya Pradesh" },
  "Bhopal":           { id: 75,   state: "Madhya Pradesh" },
  "Chandigarh":       { id: 69,   state: "Chandigarh" },
  "Amritsar":         { id: 76,   state: "Punjab" },
  "Thiruvananthapuram":{ id: 40,  state: "Kerala" },
  "Trivandrum":       { id: 40,   state: "Kerala" },
  "Kochi":            { id: 41,   state: "Kerala" },
  "Cochin":           { id: 41,   state: "Kerala" },
  "Kozhikode":        { id: 42,   state: "Kerala" },
  "Calicut":          { id: 42,   state: "Kerala" },
  "Thrissur":         { id: 43,   state: "Kerala" },
  "Salem":            { id: 34,   state: "Tamil Nadu" },
  "Trichy":           { id: 35,   state: "Tamil Nadu" },
  "Tiruchirappalli":  { id: 35,   state: "Tamil Nadu" },
  "Tirunelveli":      { id: 36,   state: "Tamil Nadu" },
  "Vellore":          { id: 37,   state: "Tamil Nadu" },
  "Pondicherry":      { id: 39,   state: "Tamil Nadu" },
  "Puducherry":       { id: 39,   state: "Tamil Nadu" },
  "Surat":            { id: 62,   state: "Gujarat" },
  "Vadodara":         { id: 63,   state: "Gujarat" },
  "Rajkot":           { id: 64,   state: "Gujarat" },
  "Bhavnagar":        { id: 65,   state: "Gujarat" },
  "Udaipur":          { id: 67,   state: "Rajasthan" },
  "Jodhpur":          { id: 77,   state: "Rajasthan" },
  "Patna":            { id: 70,   state: "Bihar" },
  "Ranchi":           { id: 72,   state: "Jharkhand" },
  "Bhubaneswar":      { id: 78,   state: "Odisha" },
  "Cuttack":          { id: 79,   state: "Odisha" },
  "Guwahati":         { id: 80,   state: "Assam" },
  "Varanasi":         { id: 81,   state: "Uttar Pradesh" },
  "Agra":             { id: 82,   state: "Uttar Pradesh" },
  "Kanpur":           { id: 83,   state: "Uttar Pradesh" },
  "Dehradun":         { id: 84,   state: "Uttarakhand" },
  "Haridwar":         { id: 85,   state: "Uttarakhand" },
  "Rishikesh":        { id: 86,   state: "Uttarakhand" },
  "Manali":           { id: 87,   state: "Himachal Pradesh" },
  "Shimla":           { id: 88,   state: "Himachal Pradesh" },
  "Jammu":            { id: 89,   state: "Jammu & Kashmir" },
  "Raipur":           { id: 96,   state: "Chhattisgarh" },
  "Shirdi":           { id: 97,   state: "Maharashtra" },
  "Nanded":           { id: 98,   state: "Maharashtra" },
  "Latur":            { id: 99,   state: "Maharashtra" },
  "Sangli":           { id: 100,  state: "Maharashtra" },
  "Satara":           { id: 101,  state: "Maharashtra" },
};

module.exports = CITIES;
